### ISSUE TITLE
Style does not seem to do anything

### ISSUE THREAD

**Issue by xbmcnut** [custom-cards/circle-sensor-card#11]
Forgive me, long-time HA user but newbie with Lovelace.

I am playing around with the style attributes with a single entity on a single page and changing the height and width values from 75px to 10px does nothing. I know I must be doing something stupid but if someone could point me in the right direction, that would be appreciated.

**Comment by jeradM** [comment]
There is no `style` config option for this card and you can't resize it - the size of the svg is based on the size of the card which is determined by the frontend. You could use it inside a horizontal stack to limit the size of the card though

**Comment by xbmcnut** [comment]
Thanks, understood. You have style conditions in your example which is what confused me. Have used a combo of vertical and horizontal stacks to achieve 8 dials across my page.
